themeTree="""
/static/
/static/css/
/static/js/
/static/img/
/static/fonts/
/static/videos/
/medium/
/medium/base.omni
/medium/orders/
/medium/orders/base.omni
/medium/orders/index.omni
/medium/orders/list.omni
/medium/orders/recover_order.omni
/medium/orders/closed.omni
/medium/overlay/
/medium/overlay/base.omni
/medium/overlay/index.omni
/medium/overlay/closed.omni
/medium/account/base.omni
/medium/account/closed.omni
/medium/account/index.omni
/medium/account/login.omni
/medium/account/password_recover.omni
/medium/carts/
/medium/carts/base.omni
/medium/carts/closed.omni
/medium/carts/index.omni
/medium/carts/address.omni
/medium/carts/customer.omni
/medium/carts/cupom.omni
/medium/carts/email_validation.omni
/medium/carts/payment.omni
/medium/carts/review.omni
/medium/carts/shipping.omni
/medium/carts/shipping_price.omni
/medium/carts/tracking.omni
/medium/catalog/
/medium/catalog/base.omni
/medium/catalog/closed.omni
/medium/catalog/index.omni
/medium/catalog/results.omni
/medium/catalog/detail.omni
/medium/catalog/landingpage.omni
/medium/customer/
/medium/customer/base.omni
/medium/customer/closed.omni
/medium/customer/index.omni
/medium/customer/contact_form.omni
/medium/customer/faq.omni
/medium/home/
/medium/home/base.omni
/medium/home/closed.omni
/medium/home/index.omni
/medium/base.omni
/medium/404.omni
/medium/5xx.omni
/medium/macros.omni
/medium/manifest.json
/small/
/small/base.omni
/small/orders/
/small/orders/base.omni
/small/orders/index.omni
/small/orders/list.omni
/small/orders/recover_order.omni
/small/orders/closed.omni
/small/overlay/
/small/overlay/base.omni
/small/overlay/index.omni
/small/overlay/closed.omni
/small/account/base.omni
/small/account/closed.omni
/small/account/index.omni
/small/account/login.omni
/small/account/password_recover.omni
/small/carts/
/small/carts/base.omni
/small/carts/closed.omni
/small/carts/index.omni
/small/carts/address.omni
/small/carts/customer.omni
/small/carts/cupom.omni
/small/carts/email_validation.omni
/small/carts/payment.omni
/small/carts/review.omni
/small/carts/shipping.omni
/small/carts/shipping_price.omni
/small/carts/tracking.omni
/small/catalog/
/small/catalog/base.omni
/small/catalog/closed.omni
/small/catalog/index.omni
/small/catalog/results.omni
/small/catalog/detail.omni
/small/catalog/landingpage.omni
/small/customer/
/small/customer/base.omni
/small/customer/closed.omni
/small/customer/index.omni
/small/customer/contact_form.omni
/small/customer/faq.omni
/small/home/
/small/home/base.omni
/small/home/closed.omni
/small/home/index.omni
/small/base.omni
/small/404.omni
/small/5xx.omni
/small/macros.omni
/small/manifest.json
/large/
/large/base.omni
/large/orders/
/large/orders/base.omni
/large/orders/index.omni
/large/orders/list.omni
/large/orders/recover_order.omni
/large/orders/closed.omni
/large/overlay/
/large/overlay/base.omni
/large/overlay/index.omni
/large/overlay/closed.omni
/large/account/base.omni
/large/account/closed.omni
/large/account/index.omni
/large/account/login.omni
/large/account/password_recover.omni
/large/carts/
/large/carts/base.omni
/large/carts/closed.omni
/large/carts/index.omni
/large/carts/address.omni
/large/carts/customer.omni
/large/carts/cupom.omni
/large/carts/email_validation.omni
/large/carts/payment.omni
/large/carts/review.omni
/large/carts/shipping.omni
/large/carts/shipping_price.omni
/large/carts/tracking.omni
/large/catalog/
/large/catalog/base.omni
/large/catalog/closed.omni
/large/catalog/index.omni
/large/catalog/results.omni
/large/catalog/detail.omni
/large/catalog/landingpage.omni
/large/customer/
/large/customer/base.omni
/large/customer/closed.omni
/large/customer/index.omni
/large/customer/contact_form.omni
/large/customer/faq.omni
/large/home/
/large/home/base.omni
/large/home/closed.omni
/large/home/index.omni
/large/base.omni
/large/404.omni
/large/5xx.omni
/large/macros.omni
/large/manifest.json
"""